# Generated by Django 4.2.1 on 2023-05-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_eat_pizzas', 'Can eat pizzas')]},
        ),
    ]
