# Generated by Django 4.2 on 2023-05-02 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Когда создан')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменён')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Когда создан')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменён')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('article', models.CharField(db_index=True, max_length=250, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
