# Generated by Django 4.2.1 on 2023-05-04 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
