# Generated by Django 4.2.1 on 2023-05-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_category_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='manager',
        ),
        migrations.AddField(
            model_name='category',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
